### ISSUE TITLE
Item Frame missing/broken texture

### ISSUE THREAD

**Issue by JackyD4Goost** [ShadySalesGnome/Doku-s-RPG#1]
**Broken Texture File Name(s):**

- Item Frames

**Minecraft Version:**

- 1.21

**Screenshots If Available:**

- 
![image](https://github.com/ShadySalesGnome/Doku-s-RPG/assets/93034172/b8c42611-7122-4fa4-957f-952c755495c1)
![image](https://github.com/ShadySalesGnome/Doku-s-RPG/assets/93034172/a31d3efd-b8ce-477c-9227-195ddd6d8a7a)

**Other Information If Available:**

- I checked the texture pack, and the were textures for Item Frames, but they didn't really work.
- I'm unsure if this is my issue or not, but I am using the alpha version of Fabulously Optimized Modpack.

**Comment by ShadySalesGnome** [comment]
Just checked without any mods, same issue, going to try to figure it out, then I'll upload a new pack version.

Edit: figured it out, when I made it I didn't realize Optifine had been working around a mistake I made with the model file and was making it work anyway, working on recreating the model now.

**Comment by ShadySalesGnome** [comment]
Should be working now, tested without mods and with Fabulously Optimized.

**Comment by JackyD4Goost** [comment]
Yup, works great and looks amazing.
This texture pack was one of my favourites and Im glad someone picked it up.
I'm very thankful that you actually listened to bug reports despite barely having anyone using the pack. ( •̀ ω •́ )✧
