### ISSUE TITLE
Missing Netherite Boot Bottom

### ISSUE THREAD

**Issue by JackyD4Goost** [ShadySalesGnome/Doku-s-RPG#2]
**Missing Texture File Name(s):**

- Netherite Armor (Boots)

**Minecraft Version:**

- 1.21

**Other Information If Available:**

- Not sure if this was intentional / accurate to the old version (I dont remember)
 But the texture for the bottom of the boot is missing and it looks kinda weird during flight
![image](https://github.com/ShadySalesGnome/Doku-s-RPG/assets/93034172/f7b01c31-1372-461c-9465-13e4b72022ef)

**Comment by JackyD4Goost** [comment]
It kinda looks like Im wearing really long jeans 😂

**Comment by ShadySalesGnome** [comment]
That does look pretty goofy, definitely not intended, It'll be fixed in the next version of the pack, also looks like the armor trim is missing, I'll fix that while I'm at it, probably going to be a little while, going to try to make a few other improvements as well.

**Comment by ShadySalesGnome** [comment]
Should be fixed now, found a few other missing things as well, those have also been fixed.
