### ISSUE TITLE
(Suggestion) Netherite tools and Iron tools looks too similar

### ISSUE THREAD

**Issue by JackyD4Goost** [ShadySalesGnome/Doku-s-RPG#3]
**Issue(s):**

- They look almost identical aside from the different tone of grey

**Minecraft Version:**

- 1.21

**Screenshots If Available:**

- 
![image](https://github.com/ShadySalesGnome/Doku-s-RPG/assets/93034172/bb61463f-9934-46fb-bc7f-e14955ac4a67)

**Other Information If Available:**

- I can tell that there is a slight color difference, but without tooltips enabled and renaming the swords, I would have a hard time telling which is which.
- Would it be possible to recolor the netherite color to a much darker silver? Or just straight up dark grey if not.

**Comment by ShadySalesGnome** [comment]
The reason they look so similar currently is that I was unhappy with the results I had when trying to make darker tools and armor,
so I went for something brighter to differentiate it from Iron.
I am trying a few different things to get a darker color without losing detail, tools are kinda working, but unfortunately the armor is proving quite difficult.

**Comment by ShadySalesGnome** [comment]
![netherite tools](https://github.com/ShadySalesGnome/Doku-s-RPG/assets/73858930/6941078b-ea9f-410d-aff1-c6f323a7f011)
I might have gone a bit too dark on these, but they are definitely distinct, still can't quite figure out the armor.

Edit: got everything including the armor as an add-on file, also includes the other variants for the netherite tools but they'll have to be swapped out manually, still not entirely satisfied with the armor but it is usable, I'll add it into the next version of the pack, I'll also start collecting alt files to upload somewhere.
[Doku's RPG Netherite Add-on.zip](https://github.com/user-attachments/files/16042360/Doku.s.RPG.Netherite.Add-on.zip)

**Comment by JackyD4Goost** [comment]
Personal opinion, I feel like a mix in with some gold parts would work considering thats the whole deal with making Netherite ingots.
Perhaps you could also use the current color scheme and slap some gold onto it to make it distinct?

**Comment by JackyD4Goost** [comment]
Also, I hope you don't think of me as annoying with all these complains.
I know working on a revival resource pack is quite a hassle having to recreate newer items with the same style and all.
I really appreciate the fact your taking your time to take in suggestions. 🙏

**Comment by ShadySalesGnome** [comment]
I have thought about trying to have a sort of netherite gold mixed look, either layered or a swirled mix, the issue I ran into for the swirled mix was that it just looked messy, and for the layered I'm not really sure how to describe it, it just looked awful on the tools and armor, I could make a layered ingot easily though, I will definitely keep trying, but as of right now it seems my level of skill leaves a bit to be desired.

I appreciate both the bug reports and the constructive criticism, I don't find it annoying in the slightest.

**Comment by ShadySalesGnome** [comment]
![mixed](https://github.com/ShadySalesGnome/Doku-s-RPG/assets/73858930/e55593b7-9655-4655-bd97-21b6eee354c7)
this is the best I've been able to do with the mixed look, still not satisfied with it, and I haven't made the armor yet, but at the very least these will be added to the alternate texture collection.

Edit: finished the armor, the mixed look is kinda growing on me, still not sure which version I'll add to the pack and which ones will be added to the alternate texture collection.

added it to the add-on file for testing.
[Doku's RPG Netherite mixed Add-on.zip](https://github.com/user-attachments/files/16046416/Doku.s.RPG.Netherite.mixed.Add-on.zip)

**Comment by JackyD4Goost** [comment]
It looks awesome, I will definitely be using this add on. 👍

**Comment by ShadySalesGnome** [comment]
Went with the mixed variant and added an alternate texture collection to Github.
